/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket;


import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Group1
 */
public class Penjualan extends javax.swing.JFrame {
   ResultSet Rs = null;
   SuperClass cls = new SuperClass();
   koneksi conn = new koneksi();
   int prid;
   int NewStok=0;
   int count = 0;
   int AvaQty = 0;
   Double UpHarga;
    /**
     * Creates new form Selling
     */
   

    public Penjualan() {
        initComponents();
        SelectJual();
        Prod.setEditable(false);
        Hrga.setEditable(false);
    }
    public void SelectJual() {
      try {
         conn.getKoneksi1();
         Rs = conn.stm.executeQuery("Select * from TABPROD");
         PTabel.setModel(DbUtils.resultSetToTableModel(Rs));
      } catch (Exception e) {
         JOptionPane.showMessageDialog(null, "Gagal memuat tabel");
      }

   }

   public void update() {
      NewStok = AvaQty - Integer.valueOf(Jmlh.getText());
      
      try {
         conn.getKoneksi2();
         String Query = "Update TABPROD set Stok=" + NewStok + " where ID=" + prid;
         Statement Add = conn.con.createStatement();
         Add.executeUpdate(Query);
         SelectJual();
      } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal Update tabel");
      }

   }

   public void bersih() {
      Hrga.setText("");
      Prod.setText("");
      Jmlh.setText("");
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Prod = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Jmlh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ClearSelling = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PTabel = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BillTxt = new javax.swing.JTextArea();
        PrintButton = new javax.swing.JButton();
        Filter = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Hrga = new javax.swing.JTextField();
        Totbay = new javax.swing.JTextField();
        Ubay = new javax.swing.JTextField();
        Ukem = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Bayar = new javax.swing.JButton();
        Log1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flazz Market");

        jPanel1.setBackground(new java.awt.Color(124, 214, 164));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("BILLING POINT");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setText("NAMA");

        Prod.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Prod.setForeground(new java.awt.Color(0, 102, 204));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("JUMLAH");

        Jmlh.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Jmlh.setForeground(new java.awt.Color(0, 102, 204));
        Jmlh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JmlhKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 153));
        jLabel7.setText("Search");

        ClearSelling.setBackground(new java.awt.Color(0, 204, 0));
        ClearSelling.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ClearSelling.setForeground(new java.awt.Color(255, 255, 255));
        ClearSelling.setText("Clear");
        ClearSelling.setBorder(null);
        ClearSelling.setBorderPainted(false);
        ClearSelling.setPreferredSize(new java.awt.Dimension(78, 43));
        ClearSelling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearSellingActionPerformed(evt);
            }
        });

        PTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "        ID", "NAME", "PRICE", "QUANTITY", "CATEGORY"
            }
        ));
        PTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PTabel);
        if (PTabel.getColumnModel().getColumnCount() > 0) {
            PTabel.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 153));
        jLabel8.setText("LIST PRODUK");

        BillTxt.setColumns(20);
        BillTxt.setRows(5);
        jScrollPane2.setViewportView(BillTxt);

        PrintButton.setText("Print");
        PrintButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrintButtonMouseClicked(evt);
            }
        });

        Filter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FilterKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 153));
        jLabel6.setText("HARGA");

        Hrga.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Hrga.setForeground(new java.awt.Color(0, 102, 204));

        Totbay.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Totbay.setForeground(new java.awt.Color(0, 102, 204));

        Ubay.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Ubay.setForeground(new java.awt.Color(0, 102, 204));

        Ukem.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Ukem.setForeground(new java.awt.Color(0, 102, 204));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 153));
        jLabel9.setText("TOTAL HARGA");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 153));
        jLabel10.setText("UANG BAYAR");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 153));
        jLabel11.setText("UANG KEMBALI");

        Bayar.setBackground(new java.awt.Color(0, 204, 0));
        Bayar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Bayar.setForeground(new java.awt.Color(255, 255, 255));
        Bayar.setText("Bayar");
        Bayar.setBorder(null);
        Bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Hrga, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Prod, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jmlh, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ubay, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Totbay, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(Ukem, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(ClearSelling, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(PrintButton)
                                .addGap(154, 154, 154))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(Filter, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Prod, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Filter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hrga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jmlh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Totbay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ubay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(PrintButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ukem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClearSelling, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Log1.setBackground(new java.awt.Color(232, 29, 29));
        Log1.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        Log1.setForeground(new java.awt.Color(255, 255, 255));
        Log1.setText("Logout");
        Log1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Log1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 99, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Log1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Log1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Log1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log1ActionPerformed
        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);
        dispose();

    }//GEN-LAST:event_Log1ActionPerformed
   
    private void ClearSellingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearSellingActionPerformed
       bersih();
    }//GEN-LAST:event_ClearSellingActionPerformed
   


    private void PTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PTabelMouseClicked
      DefaultTableModel model = (DefaultTableModel)PTabel.getModel();
      int Myindex = PTabel.getSelectedRow();
      AvaQty = Integer.valueOf(model.getValueAt(Myindex, 2).toString());
      prid = Integer.valueOf(model.getValueAt(Myindex, 0).toString());
      UpHarga = Double.valueOf(model.getValueAt(Myindex, 3).toString());
      Prod.setText(model.getValueAt(Myindex, 1).toString());
      Hrga.setText(model.getValueAt(Myindex, 3).toString());

    }//GEN-LAST:event_PTabelMouseClicked

    private void PrintButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrintButtonMouseClicked
       try {
         Thread.sleep(150L);
         BillTxt.print();
      } catch (Exception e) {
         JOptionPane.showMessageDialog(null, "Gagal Print Tagihan");
      }
      cls.setNettotal(0);
      Totbay.setText("");
      Ubay.setText("");
      Ukem.setText("");
      BillTxt.setText("");
      count=0;
    }//GEN-LAST:event_PrintButtonMouseClicked

    private void FilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FilterKeyReleased
        // TODO add your handling code here:
        String query = Filter.getText();
        filter(query);//Method Created at line no 478 
    }//GEN-LAST:event_FilterKeyReleased

    private void BayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarActionPerformed
        // TODO add your handling code here:
        cls.setUbay(Double.parseDouble(Ubay.getText()));
      
      if (cls.getUbay() < Double.parseDouble(Totbay.getText())) {
         JOptionPane.showMessageDialog(null, "Uang bayar kurang");
      } else {
         Ukem.setText(Double.toString(cls.getUkem()));
         BillTxt.setText(BillTxt.getText()+"\n-------------------------------------------------------------------------------------------------------");
         BillTxt.setText(BillTxt.getText() + "\n\t\t\tTOTAL     : Rp." + Totbay.getText());
         BillTxt.setText(BillTxt.getText() + "\n\n\t\t\tTUNAI     : Rp." + Ubay.getText());
         BillTxt.setText(BillTxt.getText() + "\n\n\t\t\tKEMBALI : Rp." + Ukem.getText());
         BillTxt.setText(BillTxt.getText()+"\n\n\n\t\t      Terima Kasih \n\t\tAtas Kunjungan Anda");
      }
    }//GEN-LAST:event_BayarActionPerformed

    private void JmlhKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JmlhKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(!isNumeric(Jmlh.getText())){
                JOptionPane.showMessageDialog(null, "Hanya bisa Memasukan angka");
            }else{
             try {
         int Quantity = Integer.parseInt(Jmlh.getText());
         if (Quantity <= 0) {
            JOptionPane.showMessageDialog(null, "Masukan angka Lebih dari 0");
            return;
         }
      } catch (NumberFormatException e) {
         JOptionPane.showMessageDialog(null, "Masukan angka positif");
      }

      if (!Jmlh.getText().isEmpty() && !Prod.getText().isEmpty()) {
         if (AvaQty < Integer.valueOf(Jmlh.getText()) || Integer.valueOf(Jmlh.getText()) <= 0) {
            JOptionPane.showMessageDialog(this, "Stok Tidak Tersedia");
            return;
         }
         
        count++;
        LocalDate Tngl = LocalDate.now();
        DateTimeFormatter formatdt = DateTimeFormatter.ofPattern("d-M-yyyy");
        String tgl = Tngl.format(formatdt);
        DateTimeFormatter formattm = DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalTime TimeNow = LocalTime.now();
        String time = TimeNow.format(formattm);
         cls.setHarga(UpHarga);
         cls.setJumlah(Double.parseDouble(Jmlh.getText()));
        
         Ubay.grabFocus();
         if (count == 1) {
            BillTxt.setText(BillTxt.getText() + "\t************FLAZZ MARKET*************\n\t\tJl.xxxxxxxx\n==========================================================\nTanggal Transaksi: "+tgl+"   "+time+"\n==========================================================\n ID    \tPRODUK    \tHARGA    \tJUMLAH    \tTOTAL\n  " + count + "      \t" + Prod.getText() + "      \t" + UpHarga + "         \t" + Jmlh.getText() + "      \t" + Double.toString(cls.getTotal()) + "\n");
         } else {
            BillTxt.setText(BillTxt.getText() + " " + count + "      \t" + Prod.getText() + "      \t" + UpHarga + "              \t" + Jmlh.getText() + "      \t" + Double.toString(cls.getTotal()) + "\n");
         }
         update();
         
            
      } else {
         JOptionPane.showMessageDialog(this, "Isi semua Data yang kosong");
      }
      Totbay.setText(Double.toString(cls.getNettotal()));
       
      
      
       try{
          PreparedStatement add = conn.con.prepareStatement("insert into history(Produk,Jumlah,Harga) values('"+Prod.getText()+"','"+Jmlh.getText()+"','"+cls.getTotal()+"')");
         
            int row = add.executeUpdate();
         }catch (SQLException e) {
           JOptionPane.showMessageDialog(null, "Gagal menambahkan ke Riwayat");
         }
      bersih();
      
            } }
    }//GEN-LAST:event_JmlhKeyPressed

    /**
     * @param args the command line arguments
     */
    public static boolean isNumeric(String str){
        return str.matches("-?\\d+(\\.\\d+)?");
    }
    private void filter(String query) {
        //Table row sorter for filter
        DefaultTableModel dm = (DefaultTableModel) PTabel.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dm);
        PTabel.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bayar;
    private javax.swing.JTextArea BillTxt;
    private javax.swing.JButton ClearSelling;
    private javax.swing.JTextField Filter;
    private javax.swing.JTextField Hrga;
    private javax.swing.JTextField Jmlh;
    private javax.swing.JButton Log1;
    private javax.swing.JTable PTabel;
    private javax.swing.JButton PrintButton;
    private javax.swing.JTextField Prod;
    private javax.swing.JTextField Totbay;
    private javax.swing.JTextField Ubay;
    private javax.swing.JTextField Ukem;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}